[package]
name = "happiness_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
linfa = "0.6.0"
linfa-trees = "0.6.0"
ndarray = "0.15.6"
ndarray-csv = "0.5.1"
